### ISSUE TITLE
Tome of magic unfinished

### ISSUE THREAD

**Issue by AncestralD** [Heliomance/HeroForge-Anew#1]
just a heads up, since you have reawakened this lovely piece of excel. there are some classes from tome of magic that are unfinished. and it seems some of the vestiges are missing too. according to the additional vestige collection.. ( some are included, others are not.)

**Comment by Heliomance** [comment]
The shadow magic and truenaming subsystems aren't in, so far as I'm aware only binding is implemented. I haven't checked vestiges - I am planning to add the online ones at some point, as I don't think they're in yet.

**Comment by AncestralD** [comment]
Sounds great. :-P if you have some thing i can help you with please say so. im not a excel wiz. but im not a newbie.

**Comment by Nitzahon** [comment]
I've actually modified my own sheet to add the zcryell vestiege,since anima mage is the best ever, I could show you if desired.I've even managed to add stuff like the damage reduction based on hd

**Comment by Heliomance** [comment]
I'm OK for content adding, I think. Thanks for the offer! Bug reports are always welcome, though - if you come across anything that doesn't work right, please, report it as an issue. Solutions are useful, but if you don't know how to fix something I'm sure I can work it out!

**Comment by AncestralD** [comment]
Nitza, could i get the version with zcryell? i kinda need it for a char im making.

**Comment by Nitzahon** [comment]
I'll try sending it your way. I may have added some other small tweaks in there that I don't remember.  any chance you could give me en e-mail? or perhaps tell me how to send private files over github?

**Comment by Heliomance** [comment]
Web content sounds like a good idea for the next thing to add, actually. Online vestiges, Swiftblade, that sort of thing. I'll start work on that soon.

**Comment by AncestralD** [comment]
Nitza, I do not know how to do that, I think im just waiting for updates.

**Comment by Heliomance** [comment]
Zceryll's in now, just to let you know.

**Comment by Nitzahon** [comment]
Huzzah!!! Bravo sir! much better implemented than what I tried to force in.  This will greatly improve the campaign I'm planning.  (The players are going to have to face past PC's who I'm going to buff up >:) ). Now all thats missing is "faiths of eberron" so I can force them to fight my favorite druid, as an unbeatable planar shepherd.

**Comment by Heliomance** [comment]
Ma'am, actually :P

You're welcome. Faiths of Eberron is on the list, though the next source is likely to be Oriental Adventures, as it's been requested for some time now.

**Comment by AncestralD** [comment]
Nice!!! Thanks a LOT. it looks soo good. and works like a charm!!

**Comment by Nitzahon** [comment]
No. Sir.
Sir is a sign of respect, regardless of gender :)
It just rolls of the tounge

**Comment by TwistedFaith84** [comment]
no offense but Ma'am is also that same sign of respect for the female gender. Which is why their is a Sir and Ma'am. Sorry I was brought up by old fashioned old schooled Irish and Italians. And if you ever called one the other you got a whooping, a lot of unfriendly words, stares, and you were corrected.

**Comment by AncestralD** [comment]
I noticed asomething with zceryll, or rather the pseudonatural template. it does not calculate the amount of Spell resistance granted.

Do you by any chance have a copy of monster forge?

**Comment by torrasque666** [comment]
this is my copy of monsterforge, and as far as i know, the last official copy anyway.
https://www.dropbox.com/s/9wrhxafuffybou2/MonsterForge%20v4.0%20beta.xls?dl=0

**Comment by AncestralD** [comment]
Thank You!!

**Comment by johnjstanton** [comment]
I have been reading about a project called xlwings that allows Python to
replace VBA in Excel files. This then allows converted Excel sheets to be
ported to free open source versions of Excel. It might be worth a peek. I
am not sure of how much VBA code there is in the sheet but Python has got
to be easier than VBA. Also this is a potentially cool and valuable thing
to know about:

http://xlwings.org/

Cheers,
John

**Comment by Heliomance** [comment]
Ooh, that's very interesting - Python is easily the language I'm most competent in. If I can shift the whole thing over to Python, that might be very useful. Thanks for the link!

Only trouble is, there's masses of code - if I have to rewrite it all manually I'll be there a very long time, and there's bits of it I don't actually understand!

**Comment by johnjstanton** [comment]
I was wondering how much VBA code there actually was but I am not surprised
that it is cryptic ;-)

In the early 1990s I wrote embedded software in C that was used to control
scientific equipment and perform data analysis.

Another group at our company (process control engineers) created software
to control material flow at mines and factories based on results from our
equipment. The PCEs used EXCEL with VBA scripts running on top of Windows
3.1. They boasted their software was so simple they didn't actually need
people who knew how to program! </sarcasm>

VBA scripts have made me queasy ever since ;-)

**Comment by Heliomance** [comment]
The most arcane bit I've come across is the three Word Wrap subs in the MiscRoutines module. If anyone can walk me through how they work, I'd be grateful - I've stared at them and I haven't got the faintest idea what's going on.

**Comment by ThAlEdison** [comment]
WordWrap: Takes a string and a target wrap length (in characters).  If the
source string is longer than the wrap, it takes a number of characters one
greater than the target from the front of the string.  It then steps
backward through the string looking for a space.  Once it finds a space, it
adds that to the output and a line feed (CHR(10)).  it then sets the next
part of the string to be processed.  Loop until completion.

NewWordWrap does the same thing, but also breaks across line feeds (CHR(10)
or vbLf).

WordWrapAbilities is way more complex.  It's called whenever CS2 or CS3
becomes active.  In both cases it's passed the parameters CSIIAbilites and
CSIIIAbilities.  This is good because it wouldn't work properly with any
other arguments.  It starts by determining the Height and Width of the
passed in cells, but it uses those values for output, and outputs to
CSIIAbilities and CSIIIAbilites regardless of which references are passed
in (that's why it only works with those parameters).  The Height and Width
are converted from points (1/72 of an Inch) to Pixels by assuming the
Microsoft default of 96 Pixels/Inch.  The formulas look complex because
they handle the non-linear default padding behavior of the cells.  The
default font is assumed to be a specific typeface and style at 16 points.
The subroutine can deal with different sizes, but not different typeface or
style.  It then stores an array of widths of printable Windows-1252
characters (code points 32-255).  At some point it splits TblAbilities into
an array, each item being a separate ability (the various ability cells had
been previously concatenated using CHR(10), so that's what it splits on).
It then loops through each of those items, and then goes letter through
letter within the item.  It prepends the proper Top Level/Sub Level bullet
(replacing the default).  It counts the width of each character to
determine if it's hit the end of the cell.  If so, it inserts a CHR(10)
into the output, and indents the next line.  It then determines if it's hit
the end of CSIIAbilities, if it has it goes to CSIIIAbilities. Otherwise it
checks if it hit the end of CSIIIAbilities, if it has it ends without
printing everything.  Finally if it hasn't hit the end of an area, it
continues processing lines.  It commits the target cell (either
CSIIAbilities or CSIIIAbilites) whenever it encounters a word boundry
character (".,;:!? ").  The complexity in the loop is due to dealing with
what happens when the output reaches one of the boundaries (width and
height).

The interesting thing about CHR(10) is that it is a line break in Excel
when word wrap is turned on, otherwise it isn't.

~Erick A. Cobb

**Comment by ThAlEdison** [comment]
The widths stored in the array are the width in pixels of the character at
16 points.  There's some interesting numbers in there.  There is a code
point in Windows-1252 for non-printing hyphen, so it has a width of 0.

~Erick A. Cobb

**Comment by Heliomance** [comment]
Closed - new content will come when it comes, no bugs here. For further general discussion, please see #53.

**Comment by photodude** [comment]
@AncestralD I stopped my contributions to add the Tome of Magic after @redmop was no longer lead.

see the original issue on the old mantis tracker http://www.heroforge.redmop.com/mantis/view.php?id=19&nbn=15#bugnotes

**Comment by redmop** [comment]
Ohh, umm. People still reference that? I guess I won't take it down then.
