### ISSUE TITLE
Gestalt not reading Second Class for Feats

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#30]
Hey I'm getting a chance to actually play a Gestalt Game with my group and when Selecting Feats it seems like the feats selection isn't reading my second class selections (Right Side) when I select feats. I'm making a Fighter 9/Samurai 9 Race is Goliath with a Draconic Templete. When scrolling through the feats it doesn't look like it's reading the fact that I'm also a Samurai and not just a Fighter

**Comment by TwistedFaith84** [comment]
And Speaking of Gestalt Games can you add another Bonus Feat Selector so people with 2 Classes can see All Bonus Feats they can choose for those 2 classes instead of 1 class at a time. Also if you can and would add the extra bonus feat selector is there a way that if you select a class from 1 list then that class isn't listed on the other ie cant select fighter twice unless you select Fighter and Fighter (Warforge Racial lvl 2)

**Comment by Heliomance** [comment]
I can't see a particularly good reason to put in a second bonus feat selector, compared to the amount of work it would be. If you have multiple feat-granting classes in non-gestalt, you still have to choose them one class at a time. Literally all that dropdown does is highlight the bonus feats available to the class you select in it - it doesn't track the feats you select by the class that granted them. I'll have a look at the gestalt behaviour, but I thought it worked - are you sure it's not granting you enough feats? What it should be doing is adding together the feats you get from all bonus feat granting classes, and telling you you have that many bonus feats. Selecting them from the right class is entirely up to you.

**Comment by ThAlEdison** [comment]
I just did a major Gestalt build and did not see this issue.
With that build,  Exotic Weapon Proficiency (Sword,  Bastard) should be
highlighted in teal/cyan,  Improved Initiative should be similarly
highlighted,  You should have 5 bonus feats,  and 9 total feats (because it
includes the 5 bonus fighter feats and 4 feats from being 9th).
9th level samurai (assuming complete warrior) doesn't have chooseable bonus
feats by that level.

I can't see a particularly good reason to put in a second bonus feat
selector, compared to the amount of work it would be. If you have multiple
feat-granting classes in non-gestalt, you still have to choose them one
class at a time. Literally all that dropdown does is highlight the bonus
feats available to the class you select in it - it doesn't track the feats
you select by the class that granted them. I'll have a look at the gestalt
behaviour, but I thought it worked - are you sure it's not granting you
enough feats? What it should be doing is adding together the feats you get
from all bonus feat granting classes, and telling you you have that many
bonus feats. Selecting them from the right class is entirely up to you.

**Comment by TwistedFaith84** [comment]
Yea sorry I looked it over and yea it is working fine. BTW do any of you know if using a Samurai and you get Two-Weapon Fighting usable for the Katana & Wakizashi if you qualify for Two-Weapon Pounce? or do you actually need to take Two-Weapon Fighting?

**Comment by ThAlEdison** [comment]
Not sure if there's an official ruling. I'm pretty sure the optimization
boards say yes, and I think most GMs would as well. However it is up in the
air.
