### ISSUE TITLE
Character Sheet Logo

### ISSUE THREAD

**Issue by chaoscommencer** [Heliomance/HeroForge-Anew#46]
The logo on Character Sheet 1 does not respect the default Campaign Selection from the Options sheet (Generic D&D 3.5).  Unless you explicitly change the campaign and then change it back to Generic D&D 3.5, The Legend of the Five Rings logo shows up.

**Comment by Heliomance** [comment]
Ayup, that's a bug. When I added in Oriental Adventures, I added the L5R logo, but didn't spot all the logic associated with it.

**Comment by Heliomance** [comment]
Hrm. I can no longer reproduce this. I don't remember fixing it, and I didn't write that I'd fixed it in the changelog, but I can't see any reason why the L5R logo would stick around from a code inspection, and I've not managed to make it stick around. I'm tentatively calling this **fixed in 8.0** unless anyone can give me more information on how to reproduce it.
