### ISSUE TITLE
Ranger's Endurance

### ISSUE THREAD

**Issue by HalfQuart** [Heliomance/HeroForge-Anew#54]
There appears to be a bug with Rangers in that it doesn't give them Endurance as a bonus feat at 3rd level. It doesn't show up in the Special Abilities section on Character Sheet 2, nor does it get highlighted in the Feats tab.... unless I'm doing something wrong?   I noticed it originally in v7.3.2.4, but also just tried it in v7.4.0.0 with the same results.

Thanks.

**Comment by Heliomance** [comment]
Bug is down to my screwing up when adding Dwarven Chanter - I managed to get it inside and AND function rather than an OR, so you don't get the feat unless you're a 2nd level Dwarven Chanter.

For some reason, you also don't get it if you're a kobold. I think that's not right.

EDIT: Oh, right, kobolds get Kobold Endurance instead.

**Comment by Heliomance** [comment]
**Fixed in 8.0**
