### ISSUE TITLE
Random Age & Height button doesn't work properly

### ISSUE THREAD

**Issue by palanthe** [Heliomance/HeroForge-Anew#79]
Dear,

I'm using version 7.4.0.0 and I'm a lazy girl. I'm making a new char with template human, but when i press the random age & height button on the Stats&Height sheet it doesn't calculate the age. Pressing re-randomize doesn't help either.

I tried also to change race to elf, but that still keeps the age at 0.

If i can help somehow let me know.

**Comment by torrasque666** [comment]
Did you select a gender?

EDIT: misread. Ignore me in favor of others.

**Comment by MonkeyBotSA** [comment]
Make sure you select a gender and a class for at least 1st level. I know
that for some races there aren't random values, although human is not one
of those, so it's possible some classes don't have values entered as well.

**Comment by Heliomance** [comment]
Starting age depends on the class. It likely won't work right if you don't have a class selected.

**Comment by TwistedFaith84** [comment]
And here I always thought Starting Age was dependent on RACE not CLASS

**Comment by jderrico** [comment]
I figured it was dependent on Race and Class because the the starting 
age has wizards starting at a later age then fighters (for example) and 
an Elf starts at a later age then a human

**Comment by torrasque666** [comment]
Its both. Your minimum starting age is dependent on race, because at minimum a PC is considered to be an adult. Each race has their own age of adulthood (Humans are like 16, Elves are like 120 or something, warforged are like 1 but that's because they are made adults, Thri-kreen are adults at 6) and then age added by class is dependent on a class being (using pathfinder terms here) Intuitive, Self-Taught, or Trained, each adding on different amounts for different races. Classes may need to be cross referenced throughout sources to determine category. One of the reasons Warlock doesn't have a starting age, since they were never given one.

**Comment by palanthe** [comment]
@Heliomance You were absolutely right, i didn't select a class yet and thus the age didn't work. Thanks for all you kind reactions and sorry for the delay (reactions to the site ended up in the wastebin).
